# fly.toml app configuration file generated for aarushishop on 2023-09-02T09:00:39+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aarushishop"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
